### ISSUE TITLE
Save output while execution

### ISSUE THREAD

**Issue by divamgupta** [omar-masmoudi/jupyter-runner#2]
Hi,

Is there anyway that the result of notebook is saved every 1 minute. This would be helpful for notebooks that take  a lot of time to run and we can see the outputs in between.

**Comment by omar-masmoudi** [comment]
Except if someone has a good idea of how to do this, this feature seem to belong more in IPython nbconvert command.
Jupyter-runner is just a wrapper for multiple IPython nbconvert commands.
