### ISSUE TITLE
Great work but how does the notebook accept parameters?

### ISSUE THREAD

**Issue by yuziGuo** [omar-masmoudi/jupyter-runner#5]
Thank you very much ! It's really a good work.
I tried to find answer to the problem below in documentations [1](https://pythonhosted.org/jupyter_runner/) and [2](https://pypi.org/project/jupyter-runner/), but failed.
My parameter-file is like:

```
root='/home/gyh/yuhe_code/MOH/exp/experiments/[191226-215741] norm_True-wn_level_1-top_k_3' JUPYTER_OUTPUT_SUFFIX=AAA
root='/home/gyh/yuhe_code/MOH/exp/experiments/[191226-223516] norm_True-wn_level_1-top_k_3-shrink_True' JUPYTER_OUTPUT_SUFFIX=AAA
```

I tried:
`jupyter-runner --parameter-file=jupyter_params plt_bertL_norm.ipynb`

but it returns:
> NameError: name 'root' is not defined
> NameError: name 'root' is not defined

Below is where I need 'root' in notebook.

 I just wrote:
```
lit_scores_cached = root+'/moh-lit-all-212_scores.npy'
met_scores_cached = root+'/moh-met-all-212_scores.npy'
```

So it seems that the parameters I set in parameter file were not passed to notebook.
But how to pass them?

**Comment by omar-masmoudi** [comment]
Sorry for the late reply, parameters are set as environment variables.

You should use 
```
import os
root = os.environ["root"]
lit_scores_cached = root+'/moh-lit-all-212_scores.npy'
met_scores_cached = root+'/moh-met-all-212_scores.npy'
```
