### ISSUE TITLE
Unfreeze tornado dependency

### ISSUE THREAD

**Issue by diricxbart** [omar-masmoudi/jupyter-runner#6]
tornado version is set to be <6, which causes dependency conflicts in environments with multiple Python packages.
The Jupyter incompatibility with tornado v6 has however already been resolved in [https://github.com/jupyter/notebook/pull/4449](https://github.com/jupyter/notebook/pull/4449).

So please remove the tornado version restriction in `setup.py` and bump the version in `jupyter_runner/__init__.py`

Please note that others have forked this repo making this exact change as well...

**Comment by omar-masmoudi** [comment]
Thanks for your suggestion.

Changed in https://github.com/omar-masmoudi/jupyter-runner/pull/7
